# Generated by Django 4.2.1 on 2025-08-28 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True, verbose_name="Адрес сайта")),
            ],
            options={
                "verbose_name": "Сайт",
                "verbose_name_plural": "Сайты",
                "db_table": "website",
            },
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Код ответа"
                    ),
                ),
                (
                    "response_time_ms",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Время ответа (мс.)"
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="Онлайн"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата запроса"
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="monitor.website",
                        verbose_name="Сайт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проверка",
                "verbose_name_plural": "Проверки",
                "db_table": "check",
                "ordering": ["-created_at"],
            },
        ),
    ]
