# Generated by Django 4.2.1 on 2025-09-27 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="check",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Результат проверки",
                "verbose_name_plural": "Результаты проверок",
            },
        ),
    ]
